apiVersion: v2
name: data-warehouse
description: A Helm chart for Kubernetes
type: application
version: 0.0.6
appVersion: 0.0.1
keywords:
- metadata
- flink
dependencies:
  - name: common
    version: 2.22.0
    repository: https://charts.bitnami.com/bitnami
  - name: elasticsearch
    version: 22.0.2
    repository: https://aaronyang0628.github.io/helm-chart-mirror/charts
    condition: elasticsearch.enabled
  - name: kafka
    version: 32.2.3
    repository: https://aaronyang0628.github.io/helm-chart-mirror/charts
    condition: kafka.enabled
  - name: flink-kubernetes-operator
    version: 1.11.0
    repository: https://aaronyang0628.github.io/helm-chart-mirror/charts
    condition: flink.enabled
