apiVersion: v2
name: data-warehouse
description: A Helm chart for Kubernetes
type: application
version: 0.0.28
appVersion: 1.11.0
keywords:
- metadata
- flink
dependencies:
  - name: common
    version: 2.22.0
    repository: https://charts.bitnami.com/bitnami
  - name: cert-manager
    version: 1.17.2
    repository: https://aaronyang0628.github.io/helm-chart-mirror/charts
    condition: certManager.enabled
  - name: minio
    version: 13.8.4
    repository: https://charts.bitnami.com/bitnami
  - name: elasticsearch
    version: 19.21.2
    repository: https://charts.bitnami.com/bitnami
  - name: kafka
    version: 29.3.14
    repository: https://charts.bitnami.com/bitnami
  - name: flink-kubernetes-operator
    version: 1.13.0
    repository: https://downloads.apache.org/flink/flink-kubernetes-operator-1.13.0/
    condition: flinkk8soperator.enabled
    alias: flinkk8soperator