apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "metadata-environment.roleName" . }}-flink-cleanup-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-delete  
    "helm.sh/hook-weight": "5"   
    "helm.sh/hook-delete-policy": hook-succeeded 
spec:
  template:
    spec:
      containers:
      - name: cleanup-container
        {{- if .Values.global.registryPrefix }}
        image: {{ .Values.global.registryPrefix }}/docker.io/bitnami/kubectl:1.28-debian-11
        {{- else }}
        image: docker.io/bitnami/kubectl:1.28-debian-11
        {{- end }}
        command: ["/bin/sh", "-c"]
        args:
        - |
          # check and delete ServiceAccount `flink`
          if kubectl get sa flink -n {{ .Release.Namespace }} >/dev/null 2>&1; then
            kubectl delete sa flink -n {{ .Release.Namespace }}
            echo "In Namespace {{ .Release.Namespace }} Deleting ServiceAccount: flink"
          else
            echo "In Namespace {{ .Release.Namespace }} ServiceAccount `flink` not found"
          fi
          
          # check and delete Role `flink`
          if kubectl get role flink -n {{ .Release.Namespace }} >/dev/null 2>&1; then
            kubectl delete role flink -n {{ .Release.Namespace }}
            echo "In Namespace {{ .Release.Namespace }} Deleting Role: flink"
          else
            echo "In Namespace {{ .Release.Namespace }}  Role `flink` not found"
          fi
          
          # check and delete RoleBinding `flink-role-binding`
          if kubectl get rolebinding flink-role-binding -n {{ .Release.Namespace }} >/dev/null 2>&1; then
            kubectl delete rolebinding flink-role-binding -n {{ .Release.Namespace }}
            echo "In Namespace {{ .Release.Namespace }} Deleting RoleBinding: flink-role-binding"
          else
            echo "In Namespace {{ .Release.Namespace }}  RoleBinding `flink-role-binding` not found"
          fi
          
          echo "Cleanup completed successfully"
      restartPolicy: Never
  backoffLimit: 1  