apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: metadata-flink-session-cluster
  namespace: {{ .Release.Namespace | quote }}
spec:
  mode: {{ .Values.flink.session.mode | quote }}
  serviceAccount: {{ include "metadata-environment.flink.serviceAccountName" . }}
  flinkVersion: {{ .Values.flink.session.version | quote }}
  image: "{{ .Values.flink.session.image.registry }}/{{ .Values.flink.session.image.repository }}:{{ .Values.flink.session.image.tag }}"
  podTemplate:
    spec:
      imagePullSecrets:
      {{- if .Values.flink.session.image.pullSecrets }}
      {{- include "common.tplvalues.render" (dict "value" .Values.flink.session.image.pullSecrets "context" $) | nindent 12 }}
      {{- end }}
      containers:
      - name: flink-main-container
        imagePullPolicy: Always
        env:
          - name: TZ
            value: Asia/Shanghai
          - name: ENABLE_BUILT_IN_PLUGINS
            value: flink-s3-fs-hadoop-1.19.1.jar
        ports:
        {{- if .Values.flink.session.extraContainerPorts }}
        {{- include "common.tplvalues.render" (dict "value" .Values.flink.session.extraContainerPorts "context" $) | nindent 12 }}
        {{- end }}
        volumeMounts:
          - name: checkpoint-volume
            mountPath: {{ .Values.flink.session.state.checkpoint.path | trimPrefix "file:///" }}
          - name: savepoint-volume
            mountPath: {{ .Values.flink.session.state.savepoint.path | trimPrefix "file:///" }}
      volumes:
        - name: checkpoint-volume
          {{- if .Values.flink.session.persistence.enabled }}
          persistentVolumeClaim:
            claimName: meta-flink-session-checkpoint-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: savepoint-volume
          {{- if .Values.flink.session.persistence.enabled }}
          persistentVolumeClaim:
            claimName: meta-flink-session-savepoint-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
  flinkConfiguration:
    env.java.opts: --add-opens java.base/java.util=ALL-UNNAMED
    state.checkpoints.dir: {{ .Values.flink.session.state.checkpoint.path }}
    state.savepoints.dir: {{ .Values.flink.session.state.savepoint.path }}
    taskmanager.numberOfTaskSlots: {{ .Values.flink.session.taskManager.taskSlots | quote }}
  jobManager:
    replicas: {{ .Values.flink.session.jobManager.replicas }}
    resource:
      {{- if .Values.flink.session.jobManager.resource }}
        cpu: {{ .Values.flink.session.jobManager.resource.cpu }}
        memory: {{ .Values.flink.session.jobManager.resource.memory }}
      {{- end }}
  taskManager:
    replicas: {{ .Values.flink.session.taskManager.replicas }}
    resource:
      {{- if .Values.flink.session.taskManager.resource }}
        cpu: {{ .Values.flink.session.taskManager.resource.cpu }}
        memory: {{ .Values.flink.session.taskManager.resource.memory }}
      {{- end }}
  {{- if .Values.flink.session.ingress.enabled }}
  ingress:
    template: {{ .Values.flink.session.ingress.template }}
    className: {{ .Values.flink.session.ingress.className }}
    annotations: {{- toYaml .Values.flink.session.ingress.annotations | nindent 6 }}
  {{- end }}
