apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.ingestTaskOperator.name }}-flink-pre-cleanup-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete  
    "helm.sh/hook-weight": "0"   
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 1  
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: cleanup-container
        {{- if .Values.global.registryPrefix }}
        image: {{ .Values.global.registryPrefix }}/docker.io/bitnami/kubectl:1.28-debian-11
        {{- else }}
        image: docker.io/bitnami/kubectl:1.28-debian-11
        {{- end }}
        command: ["/bin/sh", "-c"]
        args:
        - |
          # check and delete FlinkIngest
          if kubectl get flinkingest -n {{ .Release.Namespace }} >/dev/null 2>&1; then
            kubectl delete flinkingest -n {{ .Release.Namespace }} --all
            echo "In Namespace {{ .Release.Namespace }} Deleting All FlinkIngestTasks"
          else
            echo "In Namespace {{ .Release.Namespace }} There is no FlinkIngestTask found"
          fi

          # check and delete FlinkIngest
          if kubectl get croningest -n {{ .Release.Namespace }} >/dev/null 2>&1; then
            kubectl delete croningest -n {{ .Release.Namespace }} --all
            echo "In Namespace {{ .Release.Namespace }} Deleting All CronIngestTasks"
          else
            echo "In Namespace {{ .Release.Namespace }} There is no CronIngestTasks found"
          fi

          kubectl -n {{ .Release.Namespace }} patch flinkdeployment metadata-flink-job-ingest-kafka-to-es -p '{"metadata":{"finalizers":[]}}' --type=merge

          # check and delete FlinkDeployment 'metadata-flink-job-ingest-kafka-to-es'
          if kubectl get flinkdeployment metadata-flink-job-ingest-kafka-to-es -n {{ .Release.Namespace }} >/dev/null 2>&1; then
            kubectl delete flinkdeployment metadata-flink-job-ingest-kafka-to-es -n {{ .Release.Namespace }}
            echo "In Namespace {{ .Release.Namespace }} Deleting Flinkdeployment: metadata-flink-job-ingest-kafka-to-es"
          else
            echo "In Namespace {{ .Release.Namespace }} Flinkdeployment 'metadata-flink-job-ingest-kafka-to-es' not found"
          fi

          # check and delete sesssion job using 'metadata-flink-session-cluster'
          if kubectl get flinksessionjob -n {{ .Release.Namespace }} >/dev/null 2>&1; then
            kubectl delete flinksessionjob -n {{ .Release.Namespace }} --all
            echo "In Namespace {{ .Release.Namespace }} Deleting All SessionJobs which hosted by metadata-flink-session-cluster"
          else
            echo "In Namespace {{ .Release.Namespace }}, there is no SessionJob hosted by metadata-flink-session-cluster"
          fi

          kubectl -n {{ .Release.Namespace }}  patch flinkdeployment metadata-flink-session-cluster -p '{"metadata":{"finalizers":[]}}' --type=merge

          # check and delete FlinkDeployment 'metadata-flink-session-cluster'
          if kubectl get flinkdeployment metadata-flink-session-cluster -n {{ .Release.Namespace }} >/dev/null 2>&1; then
            kubectl delete flinkdeployment metadata-flink-session-cluster -n {{ .Release.Namespace }}
            echo "In Namespace {{ .Release.Namespace }} Deleting Flinkdeployment: metadata-flink-session-cluster"
          else
            echo "In Namespace {{ .Release.Namespace }} Flinkdeployment 'metadata-flink-session-cluster' not found"
          fi

          echo "Cleanup completed successfully"
      