{{/* First, create a list containing Release.Namespace and optional additional namespaces */}}
{{- $namespaces := list .Release.Namespace }}
{{- if .Values.flink.session.clusterNamespaces }}
{{- $namespaces = concat $namespaces .Values.flink.session.clusterNamespaces | uniq }}
{{- end }}

{{- range $namespace := $namespaces }}
---
apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: metadata-flink-session-cluster
  namespace: {{ $namespace | quote }}
spec:
  mode: {{ $.Values.flink.session.mode | quote }}
  serviceAccount: {{ include "metadata-environment.flink.serviceAccountName" $ }}
  flinkVersion: {{ $.Values.flink.session.version | quote }}
  image: "{{ $.Values.flink.session.image.registry }}/{{ $.Values.flink.session.image.repository }}:{{ $.Values.flink.session.image.tag }}"
  podTemplate:
    spec:
      securityContext:
        runAsUser: 9999
        runAsGroup: 9999
        fsGroup: 9999
      imagePullSecrets:
      {{- if $.Values.flink.session.image.pullSecrets }}
      {{- include "common.tplvalues.render" (dict "value" $.Values.flink.session.image.pullSecrets "context" $) | nindent 12 }}
      {{- end }}
      containers:
      - name: flink-main-container
        imagePullPolicy: Always
        env:
          - name: TZ
            value: Asia/Shanghai
          - name: ENABLE_BUILT_IN_PLUGINS
            value: flink-s3-fs-hadoop-1.19.1.jar
        ports:
        {{- if $.Values.flink.session.extraContainerPorts }}
        {{- include "common.tplvalues.render" (dict "value" $.Values.flink.session.extraContainerPorts "context" $) | nindent 12 }}
        {{- end }}
        volumeMounts:
          - name: shuffle-volume
            mountPath: {{ $.Values.flink.session.state.shuffle.path }}
      volumes:
        - name: shuffle-volume
          {{- if $.Values.flink.session.persistence.enabled }}
          persistentVolumeClaim:
            claimName: meta-flink-session-shuffle-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
  flinkConfiguration:
    env.java.opts: --add-opens java.base/java.util=ALL-UNNAMED  --add-opens=java.base/java.lang=ALL-UNNAMED
    flink.client.timeout: 120s
    heartbeat.timeout: "600000"
    pekko.ask.timeout: 600s
    pekko.remote.netty.tcp.connection-timeout: 600s
    io.tmp.dirs: {{ $.Values.flink.session.state.shuffle.path }}
    taskmanager.network.blocking-shuffle.compression.enabled: "true"
    taskmanager.memory.framework.off-heap.size: 256m
    taskmanager.network.sort-shuffle.min-buffers: "512"
    taskmanager.network.sort-shuffle.min-parallelism: "1"
    resourcemanager.taskmanager-timeout: "300000"
    taskmanager.numberOfTaskSlots: {{ $.Values.flink.session.taskManager.taskSlots | quote }}
  jobManager:
    replicas: {{ $.Values.flink.session.jobManager.replicas }}
    resource:
      {{- if $.Values.flink.session.jobManager.resource }}
        cpu: {{ $.Values.flink.session.jobManager.resource.cpu }}
        memory: {{ $.Values.flink.session.jobManager.resource.memory }}
      {{- end }}
  taskManager:
    replicas: {{ $.Values.flink.session.taskManager.replicas }}
    resource:
      {{- if $.Values.flink.session.taskManager.resource }}
        cpu: {{ $.Values.flink.session.taskManager.resource.cpu }}
        memory: {{ $.Values.flink.session.taskManager.resource.memory }}
      {{- end }}
    podTemplate:
      spec:
        securityContext:
          runAsUser: 9999
          runAsGroup: 9999
          fsGroup: 9999
        containers:
          - name: flink-main-container
            volumeMounts:
              - name: shuffle-volume
                mountPath: {{ $.Values.flink.session.state.shuffle.path }}
        volumes:
          - name: shuffle-volume
            {{- if $.Values.flink.session.persistence.enabled }}
            persistentVolumeClaim:
              claimName: meta-flink-session-shuffle-pvc
            {{- else }}
            emptyDir: {}
            {{- end }}
  {{- if $.Values.flink.session.ingress.enabled }}
  ingress:
    template: {{ $.Values.flink.session.ingress.template }}
    className: {{ $.Values.flink.session.ingress.className }}
    annotations: {{- toYaml $.Values.flink.session.ingress.annotations | nindent 6 }}
  {{- end }}
{{- end }}