{{- $namespaces := list .Release.Namespace }}
{{- if .Values.flink.session.clusterNamespaces }}
{{- $namespaces = concat $namespaces .Values.flink.session.clusterNamespaces | uniq }}
{{- end }}

{{- range $namespace := $namespaces }}
{{- if $.Values.flink.session.persistence.enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: meta-flink-session-shuffle-pvc
  namespace: {{ $namespace | quote }}
  labels:
    app.kubernetes.io/name: flink-session-shuffle
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: {{ include "metadata-environment.chart" $ }}
  annotations:
    # 在删除 Helm release 时保留 PVC
    "helm.sh/resource-policy": keep
spec:
  accessModes:
  {{- range $.Values.flink.session.persistence.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $.Values.flink.session.persistence.size | quote }}
  {{- if $.Values.flink.session.persistence.selector }}
  selector: {{- include "common.tplvalues.render" (dict "value" $.Values.flink.session.persistence.selector "context" $) | nindent 4 }}
  {{- end }}
  {{- if $.Values.flink.session.persistence.dataSource }}
  dataSource: {{- include "common.tplvalues.render" (dict "value" $.Values.flink.session.persistence.dataSource "context" $) | nindent 4 }}
  {{- end }}
  {{- include "common.storage.class" (dict "persistence" $.Values.flink.session.persistence "global" $.Values.global) | nindent 2 }}
{{- end }}
{{- end }}