apiVersion: batch/v1
kind: Job
metadata:
  name: metadata-kafka-topic-init-job
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    checksum/kafka-config: {{ .Values.kafka | toJson | sha256sum }}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  ttlSecondsAfterFinished: 1800
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-kafka
        {{- if .Values.global.registry }}
        image: {{ .Values.global.registry }}/{{ .Values.initJob.busybox.image }}
        {{- else }}
        image: {{ .Values.initJob.busybox.registry }}/{{ .Values.initJob.busybox.image }}
        {{- end }}
        imagePullPolicy: {{ .Values.initJob.busybox.pullPolicy }}
        command: ['sh', '-c', '
          until nc -z -w 2 {{ .Release.Name }}-kafka.{{ .Release.Namespace }}.svc.cluster.local 9092;
          do
            echo "Waiting for Kafka to be ready...";
            sleep 2;
          done;
          ']
      containers:
      - name: kafka-client
        {{- if .Values.global.registry }}
        image: {{ .Values.global.registry }}/{{ .Values.initJob.kafka.image }}
        {{- else }}
        image: {{ .Values.initJob.kafka.registry }}/{{ .Values.initJob.kafka.image }}
        {{- end }}
        imagePullPolicy: {{ .Values.initJob.kafka.pullPolicy }}
        env:
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: "{{ .Release.Name }}-kafka.{{ .Release.Namespace }}.svc.cluster.local:9092"
          - name: OPERATION
            value: "create"
          - name: TOPIC_NAME
            value: "ingest-to-es"
          - name: PARTITIONS
            value: "16"
          - name: RETENTION_MS
            value: "259200000"
          - name: REPLICATION_FACTOR
            value: {{ .Values.kafka.replicationFactor | quote }}
        command: ["/bin/bash", "-c"]
        args:
          - |
            apt-get update && apt-get install -y jq
            
            case $OPERATION in
              create)
                echo "Creating topic $TOPIC_NAME"
                kafka-topics.sh --create \
                  --bootstrap-server $KAFKA_BOOTSTRAP_SERVERS \
                  --topic $TOPIC_NAME \
                  --partitions $PARTITIONS \
                  --replication-factor $REPLICATION_FACTOR \
                  --config retention.ms=$RETENTION_MS
                ;;

              *)
                echo "Invalid operation: $OPERATION"
                exit 1
                ;;
            esac