apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-kube-conf
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.ingestTaskOperator.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.ingestTaskOperator.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.ingestTaskOperator.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  config: |-
    {{- tpl (printf `
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: %s
        server: %s
      name: local-kubernetes
    contexts:
    - context:
        cluster: local-kubernetes
        user: local-user
      name: local-kubernetes
    current-context: local-kubernetes
    kind: Config
    preferences: {}
    users:
    - name: local-user
      user:
        client-certificate-data: %s
        client-key-data: %s
    ` .Values.ingestTaskOperator.kubeConfig.cluster.certData .Values.ingestTaskOperator.kubeConfig.cluster.server  .Values.ingestTaskOperator.kubeConfig.user.certData .Values.ingestTaskOperator.kubeConfig.user.key ) . | nindent 4 }}