---
apiVersion: {{ include "common.capabilities.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "metadata-environment.clusterRoleName" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.ingestTaskOperator.commonLabels "context" $ ) | nindent 4 }}
  {{- if or .Values.ingestTaskOperator.serviceAccount.annotations .Values.ingestTaskOperator.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.ingestTaskOperator.serviceAccount.annotations .Values.ingestTaskOperator.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
    - "flink.apache.org"
    resources:
    - flinkdeployments
    - flinksessionjobs
    - flinkstatesnapshots
    verbs:
    - get
    - list
    - create
    - watch
    - patch
  - apiGroups:
    - ""
    resources:
    - configmaps
    - secrets
    - persistentvolumes
    - persistentvolumeclaims
    verbs:
    - create
    - get
    - delete
    - watch
    - list
    - update
    - patch
  - apiGroups:
    - "batch"
    resources:
    - cronjobs
    verbs:
    - create
    - get
    - delete
    - watch
    - list
  - apiGroups:
    - apiextensions.k8s.io
    resources:
    - customresourcedefinitions
    verbs:
    - get
    - list
    - watch
    - create
  - apiGroups:
    - org.zhejianglab.astro.metadata
    resources:
    - flinkingesttasks
    - virtualingesttasks
    - croningesttasks
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete


{{/* First, create a list containing Release.Namespace and optional additional namespaces */}}
{{- $namespaces := list .Release.Namespace }}
{{- if .Values.flink.session.clusterNamespaces }}
{{- $namespaces = concat $namespaces .Values.flink.session.clusterNamespaces | uniq }}
{{- end }}

{{- range $namespace := $namespaces }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "metadata-environment.serviceAccountName" $ }}
  namespace: {{ $namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $.Values.ingestTaskOperator.commonLabels "context" $ ) | nindent 4 }}
  {{- if or $.Values.ingestTaskOperator.serviceAccount.annotations $.Values.ingestTaskOperator.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list $.Values.ingestTaskOperator.serviceAccount.annotations $.Values.ingestTaskOperator.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $.Values.ingestTaskOperator.automountServiceAccountToken }}

---
apiVersion: {{ include "common.capabilities.rbac.apiVersion" $ }}
kind: Role
metadata:
  name: {{ include "metadata-environment.roleName" $ }}
  namespace: {{ $namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $.Values.ingestTaskOperator.commonLabels "context" $ ) | nindent 4 }}
  {{- if or $.Values.ingestTaskOperator.serviceAccount.annotations $.Values.ingestTaskOperator.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list $.Values.ingestTaskOperator.serviceAccount.annotations $.Values.ingestTaskOperator.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - create
      - get
      - delete
      - watch
      - list
  - apiGroups:
      - "apps/v1"  
    resources:
      - deployments
    verbs:
      - create
      - get
      - delete
  - apiGroups:
    - "batch/v1"
    resources:
      - jobs
    verbs:
      - create
      - get
      - delete
  - apiGroups:
    - org.zhejianglab.astro.metadata
    resources:
    - flinkingesttasks
    - virtualingesttasks
    - croningesttasks
    - flinkingesttasks/status
    - croningesttasks/status
    - virtualingesttasks/status
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete

---
apiVersion: {{ include "common.capabilities.rbac.apiVersion" $ }}
kind: RoleBinding
metadata:
  name: {{ printf "%s-%s" $.Values.ingestTaskOperator.serviceAccount.roleBinding.name $namespace | quote }}
  namespace: {{ $namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $.Values.ingestTaskOperator.commonLabels "context" $ ) | nindent 4 }}
  {{- if or $.Values.ingestTaskOperator.serviceAccount.annotations $.Values.ingestTaskOperator.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list $.Values.ingestTaskOperator.serviceAccount.annotations $.Values.ingestTaskOperator.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "metadata-environment.serviceAccountName" $ }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "metadata-environment.roleName" $ }}


---
apiVersion:  {{ include "common.capabilities.rbac.apiVersion" $ }}
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-%s" $.Values.ingestTaskOperator.serviceAccount.clusterRoleBinding.name $namespace | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" $.Values.ingestTaskOperator.commonLabels "context" $ ) | nindent 4 }}
  {{- if or $.Values.ingestTaskOperator.serviceAccount.annotations $.Values.ingestTaskOperator.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list $.Values.ingestTaskOperator.serviceAccount.annotations $.Values.ingestTaskOperator.commonAnnotations ) "context" . ) }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "metadata-environment.serviceAccountName" $ }}
  namespace: {{ $namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "metadata-environment.clusterRoleName" $ }}
{{- end }}