apiVersion: batch/v1
kind: Job
metadata:
  name: metadata-minio-bucket-init-job
  namespace: {{ .Release.Namespace }}
  annotations: {}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  ttlSecondsAfterFinished: 1800
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-minio
        {{- if .Values.global.registryPrefix }}
        image: {{ .Values.global.registryPrefix }}/{{ .Values.initJob.busybox.image }}
        {{- else }}
        image: {{ .Values.initJob.busybox.registry }}/{{ .Values.initJob.busybox.image }}
        {{- end }}
        imagePullPolicy: {{ .Values.initJob.busybox.pullPolicy }}
        command: ['sh', '-c', '
          until nc -z -w 2 {{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc.cluster.local 9000;
          do
            echo "Waiting for MinIO to be ready...";
            sleep 2;
          done;
          ']
      containers:
      - name: minio-client
        {{- if .Values.global.registryPrefix }}
        image: {{ .Values.global.registryPrefix }}/{{ .Values.initJob.minio.image }}
        {{- else }}
        image: {{ .Values.initJob.minio.registry }}/{{ .Values.initJob.minio.image }}
        {{- end }}
        imagePullPolicy: {{ .Values.initJob.minio.pullPolicy }}
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          echo "starting..."
          mc alias set myminio http://{{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc.cluster.local:9000 admin password
          mc mb myminio/flink
          mc anonymous set public myminio/flink
          echo "make the bucket 'myminio/flink' public successfully"