apiVersion: batch/v1
kind: Job
metadata:
  name: metadata-minio-bucket-init-job
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
  annotations:
    checksum/minio-secret: {{ include (print $.Template.BasePath "/minio-secret.yaml") . | sha256sum }}
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 1
  ttlSecondsAfterFinished: 1800
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: wait-for-minio
        {{- if .Values.global.registry }}
        image: {{ .Values.global.registry }}/{{ .Values.initJob.busybox.image }}
        {{- else }}
        image: {{ .Values.initJob.busybox.registry }}/{{ .Values.initJob.busybox.image }}
        {{- end }}
        imagePullPolicy: {{ .Values.initJob.busybox.pullPolicy }}
        command: ['sh', '-c', '
          until nc -z -w 2 {{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc.cluster.local 9000;
          do
            echo "Waiting for MinIO to be ready...";
            sleep 2;
          done;
          ']
      containers:
      - name: minio-client
        {{- if .Values.global.registry }}
        image: {{ .Values.global.registry }}/{{ .Values.initJob.minio.image }}
        {{- else }}
        image: {{ .Values.initJob.minio.registry }}/{{ .Values.initJob.minio.image }}
        {{- end }}
        imagePullPolicy: {{ .Values.initJob.minio.pullPolicy }}
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: metadata-minio-secret
              key: s3-access-key
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: metadata-minio-secret
              key: s3-access-secret
        command: ["/bin/sh", "-c"]
        args:
        - |
          set -e
          echo "starting..."
          mc alias set myminio http://{{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc.cluster.local:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}
          {{- range .Values.minio.initBuckets }}

          # Create bucket: {{ .name }}
          if ! mc ls myminio/{{ .name }} >/dev/null 2>&1; then
            mc mb myminio/{{ .name }}
            echo "Bucket 'myminio/{{ .name }}' created successfully"
          else
            echo "Bucket 'myminio/{{ .name }}' already exists"
          fi
          {{- if .public }}

          # Set bucket to public
          mc anonymous set public myminio/{{ .name }}
          echo "Bucket 'myminio/{{ .name }}' set to public"
          {{- end }}
          {{- end }}