apiVersion: v1
kind: Secret
metadata:
  name: metadata-minio-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  s3-access-key: {{ .Values.minio.auth.accessKey | b64enc }}
  root-user: {{ .Values.minio.auth.rootUser | b64enc }}
  s3-access-secret: {{ .Values.minio.auth.secretKey | b64enc }}
  root-password: {{ .Values.minio.auth.rootPassword | b64enc }}
  s3-endpoint: {{ printf "http://%s" .Values.minio.apiIngress.hostname | b64enc }}