name: publish-chart-to-harbor-registry
run-name: ${{ gitea.actor }} is testing out Gitea Push Chart 🚀
on: [push]

env:
  REGISTRY: harbor.zhejianglab.com
  USER: byang628@zhejianglab.com
  REPOSITORY_NAMESPACE: ay-dev
  CHART_NAME: data-warehouse
jobs:
  build-and-push-charts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        include:
          - chart_path: "environments/helm/metadata-environment"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release Chart
        uses: flownative/action-helm-release@v2.0.1
        with:
          charts_folder: 'environments/helm/metadata-environment'
          chart_name: 'data-warehouse'
          chart_version: 0.0.20
          app_version: 1.11.0
          registry_host: '${{ env.REGISTRY }}'
          repository_path: '${{ env.REPOSITORY_NAMESPACE }}'
          repository_user: '${{ env.USER }}'
          repository_password: '${{ secrets.ZJ_HARBOR_TOKEN }}'