name: publish-chart-to-harbor-registry
run-name: ${{ gitea.actor }} is testing out Gitea Push Chart 🚀
on: [push]

env:
  REGISTRY: harbor.zhejianglab.com
  USER: byang628@zhejianglab.com
  REPOSITORY_NAMESPACE: ay-dev
  CHART_NAME: data-warehouse
jobs:
  build-and-push-charts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        include:
          - chart_path: "environments/helm/metadata-environment"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config user.name "${{ gitea.actor }}"
          git config user.email "${{ env.USER }}"

      - name: Release Chart
        uses: bitdeps/helm-oci-charts-releaser@v0.1.4
        with:
          oci_registry: oci://harbor.zhejianglab.com/ay-dev
          oci_username: ${{ env.USER }}
          oci_password: ${{ secrets.ZJ_HARBOR_TOKEN }}
          github_token: ${{ secrets.ZJ_HARBOR_TOKEN }}
          charts_dir: "${{ matrix.chart_path }}"
          skip_existing: false
          skip_gh_release: true