name: publish-chart-to-harbor-registry
run-name: ${{ gitea.actor }} is testing out Gitea Push Chart 🚀
on: [push]

env:
  REGISTRY: harbor.zhejianglab.com
  USER: byang628@zhejianglab.com
  REPOSITORY_NAMESPACE: ay-dev

jobs:
  build-and-push-charts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        include:
          - chart_path: "environments/helm/metadata-environment"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Cache Helm
        id: cache-helm
        uses: actions/cache@v3
        with:
          path: ~/helm
          key: helm-${{ runner.os }}-${{ hashFiles('~/.helm/version') }}

      - name: Install Helm
        if: steps.cache-helm.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/helm
          wget -q -O helm.tar.gz https://files.m.daocloud.io/get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz
          tar -zxvf helm.tar.gz -C ~/helm
          mv ~/helm/linux-amd64/helm ~/helm/
          echo "${HOME}/helm" >> $GITHUB_PATH
        shell: bash

      - name: Verify Helm installation
        run: helm version

      - name: Package Helm chart
        run: helm package ${{ matrix.chart_path }}
          
      - name: Login to Harbor
        run: |
          echo "${{ secrets.ZJ_HARBOR_TOKEN }}" | helm registry login \
            ${{ env.REGISTRY }} \
            --username ${{ env.USER }} \
            --password-stdin

      - name: Push Helm chart
        run: |
          # 切换到正确的chart目录
          cd ${{ matrix.chart_path }}
          
          # 获取chart版本和名称
          CHART_VERSION=$(helm show chart . | awk '/^version:/ {print $2}' | xargs)
          CHART_NAME=$(helm show chart . | awk '/^name:/ {print $2}' | xargs)
          
          # 返回到打包后的文件所在目录
          cd - 
          
          # 推送chart
          echo "Pushing chart: ${CHART_NAME}-${CHART_VERSION}.tgz"
          helm push ${CHART_NAME}-${CHART_VERSION}.tgz oci://${{ env.REGISTRY }}/${{ env.REPOSITORY_NAMESPACE }}