apiVersion: org.zhejianglab.astro/v1
kind: MetadataIngestTask
metadata:
  name: ingest-table-from-db
spec:
  path: "jdbc:postgresql://<host>:<port>/<database_name>"
  timeout: 20
  flinkJobConfig:
    flinkVersion: v1_20
    flinkConfiguration:
      taskmanager.numberOfTaskSlots: "2"
    jobManager:
      resource:
        memory: "2048m"
        cpu: 1
    taskManager:
      resource:
        memory: "2048m"
        cpu: 1
    job:
      jarURI: local:///opt/flink/examples/streaming/StateMachineExample.jar
      parallelism: 2
      upgradeMode: stateless
  scanConfig:
    tags:
      - CRAFTS_SPECTRUM_ORIGINAL
      - FAST
    userProperties:
      key1: "value1"
      key2: "1231"
      key3: "true"
  platform: jdbc
  extraSecret: database-credientials

