apiVersion: org.zhejianglab.astro/v1
kind: MetadataIngestTask
metadata:
  name: ingest-table-from-db
spec:
  path: "jdbc:postgresql://<host>:<port>/<database_name>"
  timeout: 20
  scanConfig:
    tags:
      - CRAFTS_SPECTRUM_ORIGINAL
      - FAST
    userProperties:
      key1: "value1"
      key2: 1231
      key3: true
  platform: jdbc
  extraSecret: database-credientials

