apiVersion: org.zhejianglab.astro/v1
kind: MetadataIngestTask
metadata:
  name: test1
spec:
  path: "fs://adcp/crafts/HI/ZD2021_1_2/Dec-0619_04_05/20211201"
  timeout: 20
  scanConfig:
    tags:
      - CRAFTS_SPECTRUM_ORIGINAL
      - FAST
    userProperties:
      key1: "value1"
      key2: 1231
      key3: true
    pathPatterns:
      bucketName: "[^/]*\\/([^/]+)\\/.*"
    allowedSuffixes:
      - fits
  platform: file-system
  extraSecret: nfs-credientials
