apiVersion: org.zhejianglab.astro.metadata/v1
kind: FlinkIngestTask
metadata:
  name: ingest-table-or-fits-from-s3-qppp10
spec:
  paths: 
    - "s3://csst/test"
  allowedSuffixes:
    - fits
  platform: s3
  extraEnvs:
    esHost: "warehouse-elasticsearch.warehouse.svc.cluster.local"
    esPort: 9200
    datasetIndex: "datasetindex"
  extraSecret: 
    name: minio-ingestion-credential
    namespace: warehouse
    accessKeyName: access-key
    secretKeyName: secret-key
    endpointKeyName: s3-endpoint