apiVersion: org.zhejianglab.astro.metadata/v1
kind: FlinkIngestTask
metadata:
  name: ingest-table-or-fits-from-s3-small
spec:
  paths: 
    - "s3://csst-prod/CSST_L0/MSC/SCI/60310/10100000019/MS"
  allowedSuffixes:
    - fits
  platform: s3
  extraEnvs:
    esHost: "warehouse-elasticsearch.metadata.svc.cluster.local"
    esPort: 9200
    datasetIndex: "datasetindex"
  extraSecret: 
    name: munge-oss-ingestion-credential
    namespace: metadata
    accessKeyName: access-key
    secretKeyName: secret-key
    endpointKeyName: s3-endpoint