apiVersion: org.zhejianglab.astro.metadata/v1
kind: VirtualIngestTask
metadata:
  name: ingest-table-or-fits-from-nothing
spec:
  path: "s3://adcp/crafts/HI/ZD2021_1_2/Dec-0619_04_05/20211201"
  timeout: 20
  tags:
    - CRAFTS_SPECTRUM_ORIGINAL
    - FAST
  userProperties:
    key1: "value1"
    key2: "1231"
    key3: "true"
  pathPatterns:
    bucket_name: "[^/]*\\/([^/]+)\\/.*"
  allowedSuffixes:
    - fits
    - parquet
  platform: virtual
  jobParallelism: 4
  taskSlots: 4
  extraSecret: munge-oss-credientials