apiVersion: org.zhejianglab.astro.metadata/v1
kind: FlinkIngestTask
metadata:
  name: ingest-table-or-fits-from-s3-small
spec:
  path: "s3://csst-prod/CSST_L0/MSC/SCI/60310/10100000009/MS"
  allowedSuffixes:
    - fits
  platform: s3
  jobParallelism: 2
