package org.zhejianglab.astro;

import com.sun.net.httpserver.HttpServer;
import io.javaoperatorsdk.operator.Operator;
import java.io.IOException;
import java.net.InetSocketAddress;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.zhejianglab.astro.probes.LivenessHandler;
import org.zhejianglab.astro.probes.StartupHandler;
import org.zhejianglab.astro.reconciler.MetadataOperatorFlinkReconciler;
import org.zhejianglab.astro.reconciler.MetadataOperatorJavaReconciler;

public class Runner {

  private static final Logger log = LoggerFactory.getLogger(Runner.class);

  private static final String K8S_CLUSTER_SERVER_ADDR = "K8S_CLUSTER_SERVER_ADDR";

  private static final String K8S_CLUSTER_CERT = "K8S_CLUSTER_CERT";

  private static final String K8S_USER_KEY = "K8S_USER_KEY";

  private static final String K8S_USER_CERT = "K8S_USER_CERT";

  /**
   * Main entry point for the Metadata Ingest Operator. ## remember to add the following environment
   * variables: METADATA_OPERATOR_MODE=dev or prod and apply the following command: kubectl apply -f
   * ./target/classes/META-INF/fabric8/metadataingesttasks.org.zhejianglab.astro-v1.yml
   *
   * @param args
   * @throws IOException
   */
  public static void main(String[] args) throws IOException {
    log.info("Metadata Ingest Operator starting!");
    // Config config =
    //     new ConfigBuilder()
    //         .withMasterUrl(EnvUtil.getEnv(K8S_CLUSTER_SERVER_ADDR, "https://192.168.58.2:8443"))
    //         .withCaCertData(
    //             EnvUtil.getEnv(
    //                 K8S_CLUSTER_CERT,
    //
    // "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJME1EWXlOekEyTURZek1Gb1hEVE0wTURZeU5qQTJNRFl6TUZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS25NCm9LTUZGNVVZbWF2Q1BRZGhpQURXZWtDOHNDT0xGZ3dPdjhvQm0yNUYvQk1yUjVzUjRMUlhhVDh3UHdkQWtubWgKQXA4ZTJjYVp1RnNJTHYwUHJpaTJBYUhKUThGQ1dUbk1MMnF2SVVWQVplTnFBbENNcTVxMk1GUnlQOXhZV2c2eQpVYmhJRlcwYlVUZ01KSG1XMVNtemloOERDZkYrdzc5UFN3dXJaSklVdWJnVWhzOFNJWGlScWhjbEJSS3FiWWhICjdEZHhMR25CU2U1c204YTlINTA3RVg4QmZpMzRFZXpuemJpNzdZdXZ0VkwrcU5KOTBBVnlTd3Y3MHB6bE1jVHYKVWF6cStab2ZUc1UwSytRbFBsV05LYVo1UkptUEx0VTVrRy9id2ZPclNNSFp6NTFTVlJXcXFseTlkZkNJQVhrSwo4RUMrWENISVIwZDVwbUxhaFBzQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJSY1VzSjZlTVhYajArS2thaG9OV3dxODhrWlB6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFsaVRoSW5pagozVE0wQUNYNUIwS0RpK0tEN3A1emQzWlR6R1dDK2RmazJqTG5MaVhzcFhtZC92ZXhBMzVkUU1BMWdFSWxLQXBpCmJBZE1PRTNiOU1pYXNJZUFPOEVDTHdaaVMwYi9FWU9MNE5qQXllSzRpL3F1NE5MYU9DQXVvQnduQktpem12YVEKeVFOUFMvbXpWeEV1SzdsUWRpMUVpRFdpNzAxcVd4M1YxRi90VjRneEtNNFBWUDBUVjZpSDJHRVFGQ1VzNVBpdgoxQ3FtMjJJc3VySE92dldFNmpEN2U2dTUzWGs3eTFZOGVBZFptM3gxYzQ3MmlRQWZMWktKNGNZV1NSbzJ3ckJjCjdHWFVJc3VhdFV4TlJJUzN0eGUwYjFIVVZ2eFZiUEI0TnZQMVBOR3JDVUFycGVVVHBseXBjWklRM3BkZGgrQzkKRDMyUXZlc01oekxpRXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="))
    //         .withClientCertData(
    //             EnvUtil.getEnv(
    //                 K8S_USER_KEY,
    //
    // "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURJVENDQWdtZ0F3SUJBZ0lCQWpBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJMU1EUXlNREEyTXpJek9Wb1hEVEk0TURReU1EQTJNekl6T1Zvd01URVhNQlVHQTFVRQpDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGakFVQmdOVkJBTVREVzFwYm1scmRXSmxMWFZ6WlhJd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEZGRiVU5MdVptelZkTjl5TTFNb3k0MzZnQXRmczcKY2R4SzRRM25KM1NVWTVXMDA1MDJmWjlybjR3MmlwcTBtWER6WWV2US90RWc4UlhEUjN1UnlobzJId2pNMmcwQgp2Mkt2Q3RkNTNzbDNISVRpV3RoNUVtRjBiOFNJM1gvQmtYQjZqN1VQaVdzYWRZN0s0alNvVUNmKzNteXJ4c3NWCmJwNmVaNlRKTnJMcFl1b2Y3TndRVW5OeWdFekplYmc5TFJvRGVINHNLRXZXRnlnNEdFSFdBUEs0S0dCeGhpd1YKN3pxNWczOWFTSXhscmRKc1dFR1FTQVd3UGhuQUxsWUNRQUpyaG5mQ2dib0FjY3ZxQVVqRmpsUDZhSlRtb2p5VwpVbjBvSjVQNmhOS2VubmZjcHByTUp2MnZyTWZ4WmE1VkxkZ3kwdmcrMXFWcU9jY1pFKzVIV0lWN0FnTUJBQUdqCllEQmVNQTRHQTFVZER3RUIvd1FFQXdJRm9EQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUgKQXdJd0RBWURWUjBUQVFIL0JBSXdBREFmQmdOVkhTTUVHREFXZ0JSY1VzSjZlTVhYajArS2thaG9OV3dxODhrWgpQekFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBU0J6c0lVQTJMK3Jub1VVUjVKWkxpT096bVhjZmhSc1ZJWFZXCjhpWnRMNGlLZUpGa0ZrRjFDYk93RDhhTkFyMndsRkR3U2lJQVEyYlpTNDJhRUNaNmpONk5PV1pjT3RkVXpMUXIKZjFoVDhHK1dKL1JVL0JKbHdDVmN4V2lYYlFGNEVUdDNLVDhkZ1pUK0NyVVRNMTNXRjdqWStQbzZ5Tm83WnNyUApETmxsM1FQYWczRkJScHBKRVQvSndUZ0lyWG9ZZFgzVlBKeXExOEtaOUczZDB5eU9LVjM4SVhsSjNSaXRSSUU0CmtXYnQ4NmYra0k5Y1gyUmlYbTFjQ0pqTktrU2pSYU01ZTV0VVREWU1BczlpYkFvOEMzUGRTSlkvcEErUjNlZC8KdkNqT29zb29YUFcxR2VQVnVNZG43Qk4xRTVSNjU4TCtBTEtibkQwUjVRM3g2dE5nbkE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="))
    //         .withClientKeyData(
    //             EnvUtil.getEnv(
    //                 K8S_USER_CERT,
    //
    // "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBM1hXMURTN21aczFYVGZjak5US011TitvQUxYN08zSGNTdUVONXlkMGxHT1Z0Tk9kCk5uMmZhNStNTm9xYXRKbHc4MkhyMFA3UklQRVZ3MGQ3a2NvYU5oOEl6Tm9OQWI5aXJ3clhlZDdKZHh5RTRsclkKZVJKaGRHL0VpTjEvd1pGd2VvKzFENGxyR25XT3l1STBxRkFuL3Q1c3E4YkxGVzZlbm1la3lUYXk2V0xxSCt6YwpFRkp6Y29CTXlYbTRQUzBhQTNoK0xDaEwxaGNvT0JoQjFnRHl1Q2hnY1lZc0ZlODZ1WU4vV2tpTVphM1NiRmhCCmtFZ0ZzRDRad0M1V0FrQUNhNFozd29HNkFISEw2Z0ZJeFk1VCttaVU1cUk4bGxKOUtDZVQrb1RTbnA1MzNLYWEKekNiOXI2ekg4V1d1VlMzWU10TDRQdGFsYWpuSEdSUHVSMWlGZXdJREFRQUJBb0lCQVFDZ29iQWhUOU51M2FKbAp1c3llMlh1WTNTRk80ckRIL1Y1OE1hR1QrTnBtaDVVZkJCOFVWeW83Tmc3TndOdFdBN1laMHZ6cEt1c2xxYmpQClhCb1ZOVEt0N3ZURElhWXRqbFJXQXRjb1hxQmk5Unl0MHBjUnVuTlZzWHdzaWYwUXVoMkx5SkRjSkNDN29HbGkKWDVFeVJIRytQRGMyb1lyTWtPQWNwYkN4QWl2amU3SWdQRzREWGI4N285QU9pU0d0STV3cVZHMXhlRnpoelB5QQpVNUwybCs1RGVqYVhGNXhyOGNVaytsSzNsWFRRNW9QOWNyQlI3RnN0RnJ0T3lLZGZreFpCTGVrOVhPd0FKM0ZXCnRVeFh5ZDdLYldBc09TcndseEhHajRMeFduaVNjZ1AvMHFwZXNocmhJQmpnUmNtS3RKT3EvYTFNRVZYNEZDR1cKREpOM0NkZ0JBb0dCQVBXOTc4MnREelZ0ejZKaWdQVy9KQ3ZUb21Dby9ZNk5PSnhsY2RhMnp5ZVZFTCs2RDFQMAp5b255ZHNxdVh1V0VUQ0xPR1V3d2Q5RWJ2My9tVUYyYXhaQlBuSmdZRHFmR0YyLzduV3RDZmFtWHB0TlJ3eHE4CnlHbnlnMjhqdmVkQUxXMWtDbmJOd2pxdFM0akZwMDJlY3RWUUtVSlNuSWtyMmR5cGkyNTJaSzFCQW9HQkFPYTAKU1BwbDlPY3l4Y3l2Q3h5c3RXS2J6SzVwaTFjMWc5SitZUWx3MGt1TXI3NUR3S3Q1NTRHeHhQbFY5ZjQ0QVBzcQpKTnkwdEhtNGdIT1FRbjVESlY1RWo4WVpraUIyRERMQThkblNrQ2YrT0xIWStwU29KNzhmdjM1Y2IxSXVqL0NjCmdWL0pLVzJEMUNPQ2J5TmNXaXRNdWZPUXVjdzdDOFB6WUtPa1ZUZTdBb0dBQTk2aDBCTlJrZjNRcnpYdDRmREkKbVFnVUhvR0t2SnZzc0VuSXFTRG4waSsrdThZcVI2QXJNRkRwSGZmdzlweEd0cVdZTUdMekFBLzN6QVBNY0N6bgp2NFlCYVVPM3QxeWZNZHc4ZGx2dHJxWDhzb2N2RTFTMXN6Vm1iSEdiby9DV3hvbzB2L290Zk04TnlYR1RXTjJOCjRWNEp5RW1VdlhRN1VnWTVjOXZaYWdFQ2dZRUFqUjh4R1FLdktaSDBUdjJ3Wld6OFU0S01WUkE0N1RMT0hUK3oKYWd2Nmg3NWFicCtSUnhOOTJ1YjhYNjBHbWVoMktTMmhlT1NORlh3WUR4anFvOE85SXduN2pLbHRxcStyVEl5YwpKS3RhQlN6TVQzWXo2aVZta3RILzJITUFvWnZiN3NvOWxYTS9CVC9EejZqbEJSTmtFT0tSU1AxNXVnVlFjQi83Ck9INjRwaXNDZ1lBMFQzZERCTUgyK1BKcFJFdkZoTzRBYnR4bzhvUVU2WmRaaG50eFpwUnZ4OHpNSFYrSVJxU3UKYUZEVXFzU0drUmQ4MlJlNkJKMFE5Tm4xQWF1UVMvWjZMQlI2cEJBL01ZSEkwdzBvNWRsWUt0Mm9sVzJaR0R4cQo5QlVpUk5MU3BKdkhJWjMrcjdKQk5saDVwVnFKVFcrQ2dKbWpzY0h4b1QyMkdZMGlNbU1vWUE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo="))
    //         .build();
    // String kubeConfigPath = "/root/.kube/config2";
    // String kubeConfigContent = Files.readString(Paths.get(kubeConfigPath));
    // Config config2 = Config.fromKubeconfig(kubeConfigContent);

    Operator operator = new Operator(o -> o.withStopOnInformerErrorDuringStartup(false));

    operator.register(new MetadataOperatorFlinkReconciler());
    operator.register(new MetadataOperatorJavaReconciler());
    operator.start();

    log.info("Metadata Ingest Operator started.");

    HttpServer server = HttpServer.create(new InetSocketAddress(0), 0);
    server.createContext("/startup", new StartupHandler(operator));
    server.createContext("/healthz", new LivenessHandler(operator));
    server.setExecutor(null);
    server.start();

    log.info("Metadata Ingest Operator Healthy Probes started.");
  }
}
